// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::Language;
use glib::object::Cast;
use glib::object::ObjectType as ObjectType_;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::StaticType;
use glib::ToValue;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    pub struct LanguageManager(Object<ffi::GtkSourceLanguageManager, ffi::GtkSourceLanguageManagerClass>);

    match fn {
        get_type => || ffi::gtk_source_language_manager_get_type(),
    }
}

impl LanguageManager {
    #[doc(alias = "gtk_source_language_manager_new")]
    pub fn new() -> LanguageManager {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::gtk_source_language_manager_new()) }
    }

    #[doc(alias = "gtk_source_language_manager_get_language")]
    pub fn get_language(&self, id: &str) -> Option<Language> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_manager_get_language(
                self.to_glib_none().0,
                id.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "gtk_source_language_manager_get_language_ids")]
    pub fn get_language_ids(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::gtk_source_language_manager_get_language_ids(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "gtk_source_language_manager_get_search_path")]
    pub fn get_search_path(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(ffi::gtk_source_language_manager_get_search_path(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "gtk_source_language_manager_guess_language")]
    pub fn guess_language(
        &self,
        filename: Option<&str>,
        content_type: Option<&str>,
    ) -> Option<Language> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_manager_guess_language(
                self.to_glib_none().0,
                filename.to_glib_none().0,
                content_type.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "gtk_source_language_manager_set_search_path")]
    pub fn set_search_path(&self, dirs: &[&str]) {
        unsafe {
            ffi::gtk_source_language_manager_set_search_path(
                self.to_glib_none().0,
                dirs.to_glib_none().0,
            );
        }
    }

    #[doc(alias = "gtk_source_language_manager_get_default")]
    pub fn get_default() -> Option<LanguageManager> {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::gtk_source_language_manager_get_default()) }
    }

    pub fn connect_property_language_ids_notify<F: Fn(&LanguageManager) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_language_ids_trampoline<F: Fn(&LanguageManager) + 'static>(
            this: *mut ffi::GtkSourceLanguageManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::language-ids\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_language_ids_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    pub fn connect_property_search_path_notify<F: Fn(&LanguageManager) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_search_path_trampoline<F: Fn(&LanguageManager) + 'static>(
            this: *mut ffi::GtkSourceLanguageManager,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::search-path\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_search_path_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for LanguageManager {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Clone, Default)]
pub struct LanguageManagerBuilder {
    search_path: Option<Vec<String>>,
}

impl LanguageManagerBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn build(self) -> LanguageManager {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
        if let Some(ref search_path) = self.search_path {
            properties.push(("search-path", search_path));
        }
        let ret = glib::Object::new::<LanguageManager>(&properties).expect("object new");
        ret
    }

    pub fn search_path(mut self, search_path: Vec<String>) -> Self {
        self.search_path = Some(search_path);
        self
    }
}

impl fmt::Display for LanguageManager {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("LanguageManager")
    }
}
