[package]
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "sourceview5-sys"
version = "0.1.0"
documentation = "https://bilelmoussaoui.github.io/sourceview5-rs/sourceview5_sys/"
repository = "https://github.com/bilelmoussaoui/sourceview5-rs/"
[package.metadata.system-deps.gtksourceview_5]
name = "gtksourceview-5"
version = "4.90"

[package.metadata.system-deps.gtksourceview_5.v5_0]
version = "4.90"
[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gtk4-sys"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gdk4-sys"

[build-dependencies]
system-deps = "3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []
v5_0 = []
