[options]
external_libraries = [
    "GLib",
    "GObject",
    "Gdk",
    "GdkPixbuf",
    "Gio",
    "Gtk",
    "Pango",
]
girs_directories = ["../../gir-files"]
library = "GtkSource"
min_cfg_version = "4.90"
version = "5"
work_mode = "sys"
