[options]
deprecate_by_min_version = true
generate_safety_asserts = true
girs_directories = ["../gir-files"]
library = "GtkSource"
min_cfg_version = "4.90"
single_version_file = true
target_path = "."
version = "5"
work_mode = "normal"
generate_builder = true

external_libraries = [
    "GLib",
    "GObject",
    "Gdk",
    "GdkPixbuf",
    "Gio",
    "Gtk",
    "Pango",
]

generate = [
    # "GtkSource.RegionIter",
    "GtkSource.BackgroundPatternType",
    "GtkSource.BracketMatchType",
    "GtkSource.Buffer",
    "GtkSource.ChangeCaseType",
    "GtkSource.Completion",
    "GtkSource.CompletionActivation",
    "GtkSource.CompletionCell",
    "GtkSource.CompletionColumn",
    "GtkSource.CompletionContext",
    "GtkSource.CompletionProposal",
    "GtkSource.CompletionProvider",
    "GtkSource.CompletionSnippets",
    "GtkSource.CompletionWords",
    "GtkSource.CompressionType",
    "GtkSource.Encoding",
    "GtkSource.File",
    "GtkSource.FileLoaderError",
    "GtkSource.FileSaver",
    "GtkSource.FileSaverError",
    "GtkSource.FileSaverFlags",
    "GtkSource.Gutter",
    "GtkSource.GutterRenderer",
    "GtkSource.GutterRendererAlignmentMode",
    "GtkSource.GutterRendererPixbuf",
    "GtkSource.GutterRendererText",
    "GtkSource.Hover",
    "GtkSource.HoverContext",
    "GtkSource.HoverDisplay",
    "GtkSource.HoverProvider",
    "GtkSource.Indenter",
    "GtkSource.Language",
    "GtkSource.LanguageManager",
    "GtkSource.Map",
    "GtkSource.Mark",
    "GtkSource.MarkAttributes",
    "GtkSource.MountOperationFactory",
    "GtkSource.NewlineType",
    "GtkSource.PrintCompositor",
    "GtkSource.Region",
    "GtkSource.SearchContext",
    "GtkSource.SearchSettings",
    "GtkSource.SmartHomeEndType",
    "GtkSource.Snippet",
    "GtkSource.SnippetChunk",
    "GtkSource.SnippetContext",
    "GtkSource.SnippetManager",
    "GtkSource.SortFlags",
    "GtkSource.SpaceDrawer",
    "GtkSource.SpaceLocationFlags",
    "GtkSource.SpaceTypeFlags",
    "GtkSource.Style",
    "GtkSource.StyleScheme",
    "GtkSource.StyleSchemeChooser",
    "GtkSource.StyleSchemeChooserButton",
    "GtkSource.StyleSchemeChooserWidget",
    "GtkSource.StyleSchemeManager",
    "GtkSource.Tag",
    "GtkSource.ViewGutterPosition"
]

manual = [
    "GLib.Error",
    "GObject.Object",
    "GLib.Priority",
    "GLib.Quark",
    "GLib.Variant",
    "Gdk.ModifierType",
    "Gdk.Paintable",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "GdkPixbuf.Pixbuf",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.Icon",
    "Gio.InputStream",
    "Gio.ListModel",
    "Gio.MountOperation",
    "Gio.Settings",
    "Gio.SettingsBindFlags",
    "Gtk.Accessible",
    "Gtk.Actionable",
    "Gtk.Buildable",
    "Gtk.Button",
    "Gtk.ConstraintTarget",
    "Gtk.PrintContext",
    "Gtk.Scrollable",
    "Gtk.TextBuffer",
    "Gtk.TextIter",
    "Gtk.TextMark",
    "Gtk.TextTag",
    "Gtk.TextTagTable",
    "Gtk.TextView",
    "Gtk.TextWindowType",
    "Gtk.Unit",
    "Gtk.Widget",
    "Gtk.WrapMode",
    "Pango.AttrList",
    "Pango.FontDescription",
    "Pango.Underline",
]

[[object]]
generate_builder = true
name = "GtkSource.FileLoader"
status = "generate"
    [[object.function]]
    name = "set_candidate_encodings"
    ignore = true # manual

[[object]]
name = "GtkSource.GutterLines"
status = "generate"
    [[object.function]]
    name = "get_yrange"
    ignore = true # manual

[[object]]
name = "GtkSource.View"
status = "generate"
    [[object.function]]
    name = "get_mark_attributes"
    ignore = true # manual
    [[object.function]]
    name = "push_snippet"
    ignore = true # manual
