on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  check:
    name: build/test
    runs-on: ubuntu-20.04
    container:
      image: docker.io/bilelmoussaoui/gtk4
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.48.0"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        name: "Build"
        with:
          command: build

  regen_check:
    name: regen checker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: cp ./GtkSource-5.gir ./gir-files
      - run: python3 generator.py
      - run: rm -rf ./gir-files/GtkSource-5.gir 
      - run: git diff -R --exit-code
  
  clippy:
    name: clippy
    runs-on: ubuntu-20.04
    container:
      image: docker.io/bilelmoussaoui/gtk4
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings
  
  # checker:
  #   name: gtk-rs checker
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/checkout@v2
  #       with:
  #         repository: gtk-rs/checker
  #         ref: master
  #         path: checker
  #     - working-directory: checker
  #       run: cargo build --release
  #     - run: cargo run -- ../sourceview5
  #       working-directory: checker
  #     - run: cargo run -- ../sourceview5/sys
  #       working-directory: checker
  #     - run: ./check_init_asserts ../sourceview5
  #       working-directory: checker
